name: HyperExecute-Autosplit-2-Concurrency
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true
      sampleRepoLink:
        description: Link to the HyperExecute sample repo
        default: https://github.com/john190501/hyp-autosplit-2-report-artifact-email
        required: true

jobs:
  HyperExecute-Autosplit-2-Concurrency:
    runs-on: linux
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
  
      - name: Download the sample suite
        shell: bash
        run: |
          git clone ${{ github.event.inputs.sampleRepoLink }}
  
      - name: Download CLI and setting environment variables
        shell: bash
        run: |
          cd hyp-autosplit-2-report-artifact-email
          curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
  
      - name: Setting Environment Variables
        shell: bash
        run: |
          export LT_USERNAME=${{ github.event.inputs.username }}
          export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
          echo $LT_USERNAME
          echo $LT_ACCESS_KEY
  
      - name: Executing the Job
        shell: bash
        run: |
          ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/autosplit_linux.yaml --download-artifacts --download-report
